language: scala
scala:
- 2.11.8
- 2.12.1
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi
script:
- |
  if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
    openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport publishSigned
  else
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport
  fi
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- bash <(curl -s https://codecov.io/bash)
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION"
env:
  global: