language: scala
scala:
- 2.11.8
- 2.12.1
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi
script:
- |
  if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
    openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport publishSigned
  else
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport
  fi
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- bash <(curl -s https://codecov.io/bash)
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION"
env:
  global:
  - secure: KR3SzYsi8zBdh86zxFR+63JUHSqV+u8L7hRIrKmNxUUd1CbooNvHTcaTohNdxsR9tlkoBcpugxkUqXe7DD3kWFLOEst1FloELHfP03ViAHP4+XxxPt7ObmCm6egl/gy5TDCwpoLjpHgziMc5R/DeLncwLlBtSdNX0nedC8x5YrZzEIU0FRjVEDfsWtq+XkZtFjUQGzHpO6pFEzIeDIpaii5O1hx3uPDvbYM+Ke72z/VnO2mnCM6vqU27PzNf96FwXv3fGe6MsfR2w8PCxuOiaKcSiosfgpEB0Us50UwtlsRn9Gu6mKNvk3qhJtL97SLdbOtFCEP8khaIFrk57QcXyVbOKxBGo5liYGmP/eXWNBmOD7hGg6YWJ/uK8DAmTiTrPVOobOwzgb9L1VtrfzeBd5JLBNoMRgtoF7nQ1J0oU8fC55Bdp5jGPFiczui1pZutxW0Ekg7wLncFT/btI6eFaVz3hMbsRE2CDcxQMRaBnvV/asm5w2FCrfVZ3sFhuyvNFzIYETP06LpFKvKbYR05W72+P8recGYchn+leJtYYqCRLiT0Ll4C6B6KDn7knjWEbcrOGd1RDl0F/qBT7hoe5pumKv67zadwb/eRZCHAUOFcMf4/tJiC20mfWV0E5mGapNDG5aqwEyLzImsYDuEKPg5QBqX9xQv36o/U13g1LUE=
  - secure: 7dGalvuKltLRwQjbcCbWgF2zCo6LZraszOicq4+kY0hbBMKrP26DJEyP/+0xGco6ovGbbfzcc94mZxBijowV3k0B9TD3zUogbbYLt57cVC9fgHLily68QT6+/VZ5K3L6nFTjJwS6YDWigWGuD9kxQsS+NP2BcIXBlkLCi3jCw4bFBO0SxNWmc4uCxrLppoo+O2e+FfkfPlTfvsA0f7Qs6Zw3soDxdE/+jewZ9IOYIenqMB7dMRdYjJtWZE9EcESb47/Vm8O6DD6pg6CoQFduevRgBfaWTtfBm7zFaG3Z0ttLdMuB7JKBXWZekPYMoZcRSgVzdu9kR2/lR96jGGuV+avCoBsHpH/feeUNrSNFRvEQjt9XVoofj4jrxsFmbX79/HdY0rTnsJQmp42v1FLxQHKiqnmSQ8qd9P8+dqDmZPGczkeCgRlTSG2oKyNkpJ9S/Q0FooR7CXFwGNlpsY7cfwGf8xaBTLw1ZKFk2RE34cxZ9KDBaqG8N3qemX08bLhLH5tUpU/yY5CWXtJL3QWNf8qdMf5Ru2IQMhwmlH1mVGFvv/cUBV5Ow+eTsJz3Lr2EsrGpUO2W5Q7CA6SWEl61n1nymDTzWJLF/ECpV7uEro/OQED6YfD66wYS8JBwkdae/1RdCXn5zY8ri3gtOXk5rrFrFF8iaJ7FIBOuC9HowzA=
  - secure: qzvr4JPz6av8DWuteH3twkVizXNauYcx3D3fCgpCXDMKnaFWTl45GQLCAIbEuKJdi/cZ9ZizjheosoeNlEy57nb3DUbFwSqw8WskOZHCanrnpoewi/onouJQL2krgVBQt8n5b8DWn/w8Y6QxL8tdhFRNXQAWwEnRO+WUOTElnK3COK6jp8MUTi+oLdotqg+Gn+YFPVY8w3fALalGSh0sMb90wKB8VYXEY8wFpDLMCXpvPopeqQ5pbDfUnP33X+flN9JrJzjQcbTcn8S264SXiDKpXuL8dRQgOFVE5WR+AeWzdUhfW9RIcZdhcRqjYHiDGxcrZH+dpQqs/S5eoGrRrY5Q8lcI/BZeBwotk+Fyw01HnTKzcNy2/CYvN1r6R/30wUmcFcsaV7j77S3qanJtWxhNQsBW7mV0fqCX95PpksowppFx/oa0Gq4OofrjcL/btX2hyfOIMGKhzSGVmovFrAHga1Auq2Yzd0AK8MN8zNST76vZ8w9bY7ojdvRzkPeerbyejqhU19gwW39qPn9IPft4Bbc08TYbuo3bc9AUpWmU/BSsJ1UuwvuP1xayTYNRfrAqo3fQsX0XsbXxrc1wfq8nOdRSsnyPH/Df0sDsAuVBX6uylgIHOEoGkyedNL8xGYocbZy4MtP+S8qcVsmWRNAZAurE5tXg9mKfR4CcLaE=
